version: 2
jobs:
  build-frontend:
    docker:
      - image: circleci/node:8.12.0
    environment:
      CI: false
    working_directory: ~/repo/ironmental-frontend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      # - store_artifacts:
      #     path: ~/repo/ironmental-frontend/build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ironmental-frontend/build
  deploy-frontend:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo/ironmental-frontend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run: sudo pip install awscli
      - run: aws s3 cp ./build s3://ironmental-client/ --recursive
      - run: aws cloudfront create-invalidation --distribution-id EPZ218L5FEU8F --paths "/index.html"
      - run: aws cloudfront create-invalidation --distribution-id EVVQ7B82QDRT8 --paths "/index.html"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: master
      - deploy-frontend:
          filters:
            branches:
              only: master
          requires:
            - build-frontend

