version: 2
jobs:
  build-frontend:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo/ironmental-frontend
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/ironmental-frontend
      - restore_cache:
          keys: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: dist
  deploy-frontend:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo/ironmental-frontend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run: sudo pip install awscli
      - run: aws s3 cp ./build s3://ironmental-client/ --recursive
      - run: aws cloudfront create-invalidation --distribution-id EPZ218L5FEU8F --paths "/index.html"
      - run: aws cloudfront create-invalidation --distribution-id EVVQ7B82QDRT8 --paths "/index.html"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: master
      - deploy-frontend:
          filters:
            branches:
              only: master
          requires:
            - build-frontend

